version: '3'

services:
  labseq-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - CAFFEINE_CACHE_NAME=labseq-cache-manager
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: >
      bash -c "java -jar /app/target/labseq-0.0.1.jar"
